### ISSUE TITLE
Template for SSB Pub Operator Survey

### ISSUE THREAD

**Issue by benhylau** [austinfrey/p2p-community-infrastructure#2]
The rendered indentation looks odd [here](https://github.com/austinfrey/pub-operator-survey/issues/2#issue-528079242), I wonder if we should update the template to not use numbered lists, and instead like this.

---

# SSB Pub Operator Survey

Please answer the following questions:

Q1. What is the name / address of your pub?

>pub.solarpunk.network (`@vU/bDokQrQro6t835MkjGct+dmygIv4zkd4oV3UNhgc=.ed25519`)

Q2. Is the pub local or cloud-based? If cloud based, where is it hosted?

>Digital Ocean

Q3. When was the pub created?

>10 March 2018

**Comment by mycognosist** [comment]
That looks much neater, thanks @benhylau . I'll make a PR in a few minutes.

**Comment by austinfrey** [comment]
Looks like this the new format is working out. Closing!
